//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Certify.Locales {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Certify.Locales.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 About 的本地化字符串。
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Current Language Translator:  的本地化字符串。
        /// </summary>
        public static string About_LanguageTranslator {
            get {
                return ResourceManager.GetString("About_LanguageTranslator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Check for Updates.. 的本地化字符串。
        /// </summary>
        public static string AboutControl_CheckForUpdateButton {
            get {
                return ResourceManager.GetString("AboutControl_CheckForUpdateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enter Key.. 的本地化字符串。
        /// </summary>
        public static string AboutControl_EnterKey {
            get {
                return ResourceManager.GetString("AboutControl_EnterKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Purchase License Key.. 的本地化字符串。
        /// </summary>
        public static string AboutControl_Register {
            get {
                return ResourceManager.GetString("AboutControl_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not Registered 的本地化字符串。
        /// </summary>
        public static string AboutControl_RegistrationTypeLabel {
            get {
                return ResourceManager.GetString("AboutControl_RegistrationTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Send Feedback 的本地化字符串。
        /// </summary>
        public static string AboutControl_SendFeedback {
            get {
                return ResourceManager.GetString("AboutControl_SendFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Support 的本地化字符串。
        /// </summary>
        public static string AboutControl_Support {
            get {
                return ResourceManager.GetString("AboutControl_Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This version is free for evaluation and will manage a limited number of certificates. To remove this limitation please purchase a registration key at https://certifytheweb.com/register. Registered users can get support by emailing support@certifytheweb.com 的本地化字符串。
        /// </summary>
        public static string AboutControl_TrialDetailLabel {
            get {
                return ResourceManager.GetString("AboutControl_TrialDetailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Advanced 的本地化字符串。
        /// </summary>
        public static string Advanced {
            get {
                return ResourceManager.GetString("Advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Alert 的本地化字符串。
        /// </summary>
        public static string Alert {
            get {
                return ResourceManager.GetString("Alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ... 的本地化字符串。
        /// </summary>
        public static string Browser {
            get {
                return ResourceManager.GetString("Browser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Challenge 的本地化字符串。
        /// </summary>
        public static string Challenge {
            get {
                return ResourceManager.GetString("Challenge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Challenge Error 的本地化字符串。
        /// </summary>
        public static string ChallengeError {
            get {
                return ResourceManager.GetString("ChallengeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Comments:  的本地化字符串。
        /// </summary>
        public static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Configure Auto Renew 的本地化字符串。
        /// </summary>
        public static string Configure_Auto_Renew {
            get {
                return ResourceManager.GetString("Configure_Auto_Renew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Confirm Delete 的本地化字符串。
        /// </summary>
        public static string ConfirmDelete {
            get {
                return ResourceManager.GetString("ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add/Update Stored Credential 的本地化字符串。
        /// </summary>
        public static string Credentials_EditCredential {
            get {
                return ResourceManager.GetString("Credentials_EditCredential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stored credentials are required to make automated calls to APIs and other resources during certificate renewal and deployment. These credentials are protected using the Windows Data Protection APIs and stored on this machine. 的本地化字符串。
        /// </summary>
        public static string Credentials_Intro {
            get {
                return ResourceManager.GetString("Credentials_Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 To add this server to your dashboard, provide your https://certifytheweb.com/profile sign in details or register a new account: 的本地化字符串。
        /// </summary>
        public static string Dashboard_AddIntro {
            get {
                return ResourceManager.GetString("Dashboard_AddIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create a new account 的本地化字符串。
        /// </summary>
        public static string Dashboard_NewAccount {
            get {
                return ResourceManager.GetString("Dashboard_NewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Password 的本地化字符串。
        /// </summary>
        public static string Dashboard_Password {
            get {
                return ResourceManager.GetString("Dashboard_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add 的本地化字符串。
        /// </summary>
        public static string Dashboard_Register {
            get {
                return ResourceManager.GetString("Dashboard_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Discard Changes 的本地化字符串。
        /// </summary>
        public static string DiscardChanges {
            get {
                return ResourceManager.GetString("DiscardChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Email Address 的本地化字符串。
        /// </summary>
        public static string Email_Address {
            get {
                return ResourceManager.GetString("Email_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error 的本地化字符串。
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expired {0} days ago 的本地化字符串。
        /// </summary>
        public static string ExpiryDateConverter_CertificateExpiredNDaysAgo {
            get {
                return ResourceManager.GetString("ExpiryDateConverter_CertificateExpiredNDaysAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expired {0} hours ago 的本地化字符串。
        /// </summary>
        public static string ExpiryDateConverter_CertificateExpiredNHoursAgo {
            get {
                return ResourceManager.GetString("ExpiryDateConverter_CertificateExpiredNHoursAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expires in {0} days 的本地化字符串。
        /// </summary>
        public static string ExpiryDateConverter_CertificateExpiresIn {
            get {
                return ResourceManager.GetString("ExpiryDateConverter_CertificateExpiresIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expires in {0} hours 的本地化字符串。
        /// </summary>
        public static string ExpiryDateConverter_CertificateExpiresInNHours {
            get {
                return ResourceManager.GetString("ExpiryDateConverter_CertificateExpiresInNHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No current certificate. 的本地化字符串。
        /// </summary>
        public static string ExpiryDateConverter_NoCurrentCertificate {
            get {
                return ResourceManager.GetString("ExpiryDateConverter_NoCurrentCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 failed 的本地化字符串。
        /// </summary>
        public static string failed {
            get {
                return ResourceManager.GetString("failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Loading... 的本地化字符串。
        /// </summary>
        public static string General_Loading {
            get {
                return ResourceManager.GetString("General_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add to Reporting Dashboard 的本地化字符串。
        /// </summary>
        public static string GettingStarted_AddToDashboard {
            get {
                return ResourceManager.GetString("GettingStarted_AddToDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dashboard 的本地化字符串。
        /// </summary>
        public static string GettingStarted_Dashboard {
            get {
                return ResourceManager.GetString("GettingStarted_Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You can use the reporting dashboard to easily view certificate renewal status across one or more servers. 的本地化字符串。
        /// </summary>
        public static string GettingStarted_DashboardIntro {
            get {
                return ResourceManager.GetString("GettingStarted_DashboardIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 View Dashboard 的本地化字符串。
        /// </summary>
        public static string GettingStarted_ViewDashboard {
            get {
                return ResourceManager.GetString("GettingStarted_ViewDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import 的本地化字符串。
        /// </summary>
        public static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Merge multiple domains/certificates per site into one  Managed Certificate 的本地化字符串。
        /// </summary>
        public static string ImportDlg_Merge {
            get {
                return ResourceManager.GetString("ImportDlg_Merge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You are upgrading from an older version of Certify. This will create new  Managed Certificates which you can then edit to adjust the renewal settings etc. 的本地化字符串。
        /// </summary>
        public static string ImportDlg_OpComment {
            get {
                return ResourceManager.GetString("ImportDlg_OpComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import  Managed Certificates 的本地化字符串。
        /// </summary>
        public static string ImportDlg_OpTitle {
            get {
                return ResourceManager.GetString("ImportDlg_OpTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Skip Import 的本地化字符串。
        /// </summary>
        public static string ImportDlg_Skip {
            get {
                return ResourceManager.GetString("ImportDlg_Skip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Certify - Import 的本地化字符串。
        /// </summary>
        public static string ImportDlg_Title {
            get {
                return ResourceManager.GetString("ImportDlg_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 In Progress 的本地化字符串。
        /// </summary>
        public static string In_Progress {
            get {
                return ResourceManager.GetString("In_Progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Info 的本地化字符串。
        /// </summary>
        public static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Certify Certificate Manager Contributors （https://certifytheweb.com） 的本地化字符串。
        /// </summary>
        public static string LanguageAuthor {
            get {
                return ResourceManager.GetString("LanguageAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 License Key 的本地化字符串。
        /// </summary>
        public static string LicenseKey {
            get {
                return ResourceManager.GetString("LicenseKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Get started by registering a new contact, then you can start requesting certificates. 的本地化字符串。
        /// </summary>
        public static string MainWindow_GetStartGuideWithNewCert {
            get {
                return ResourceManager.GetString("MainWindow_GetStartGuideWithNewCert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IIS Was not detected on this server, important functionality will be unavailable. If you know IIS is installed and working on this server, please report this error to support@certifytheweb.com providing details of your server Operating System version and IIS versions 的本地化字符串。
        /// </summary>
        public static string MainWindow_IISNotAvailable {
            get {
                return ResourceManager.GetString("MainWindow_IISNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Your license key has expired or is no longer active. 的本地化字符串。
        /// </summary>
        public static string MainWindow_KeyExpired {
            get {
                return ResourceManager.GetString("MainWindow_KeyExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This will renew certificates for all auto-renewed items. Proceed? 的本地化字符串。
        /// </summary>
        public static string MainWindow_RenewAllConfirm {
            get {
                return ResourceManager.GetString("MainWindow_RenewAllConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  [Community Edition] 的本地化字符串。
        /// </summary>
        public static string MainWindow_TitleTrialPostfix {
            get {
                return ResourceManager.GetString("MainWindow_TitleTrialPostfix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You are using the evaluation version of this app. Please purchase a registration key to upgrade. See the Register option on the About tab. 的本地化字符串。
        /// </summary>
        public static string MainWindow_TrialLimitationReached {
            get {
                return ResourceManager.GetString("MainWindow_TrialLimitationReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Visit download page now? 的本地化字符串。
        /// </summary>
        public static string MainWindow_VisitDownloadPage {
            get {
                return ResourceManager.GetString("MainWindow_VisitDownloadPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Managed Certificates 的本地化字符串。
        /// </summary>
        public static string Managed_Certificates {
            get {
                return ResourceManager.GetString("Managed_Certificates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  Managed Certificates 的本地化字符串。
        /// </summary>
        public static string Managed_Sites {
            get {
                return ResourceManager.GetString("Managed_Sites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似   Deployment of your certificate can be automatic or you can perform your own deployment tasks (see the Tasks tab). 的本地化字符串。
        /// </summary>
        public static string ManagedCertificates_Deployment_Intro {
            get {
                return ResourceManager.GetString("ManagedCertificates_Deployment_Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Filter... 的本地化字符串。
        /// </summary>
        public static string ManagedCertificates_Filter {
            get {
                return ResourceManager.GetString("ManagedCertificates_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select a Managed Certificate or select New Certificate to begin. 的本地化字符串。
        /// </summary>
        public static string ManagedCertificates_NoItemSelectedTip {
            get {
                return ResourceManager.GetString("ManagedCertificates_NoItemSelectedTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Deployment Tasks run (in the order shown) after the standard Deployment process has completed (see the Deployment tab). Tasks can be run immediately after the certificate has updated or they can be deferred (to run manually or via a scheduled task etc.). You can also drag tasks to re-order them: 的本地化字符串。
        /// </summary>
        public static string ManagedCertificates_Tasks_DeploymentIntro {
            get {
                return ResourceManager.GetString("ManagedCertificates_Tasks_DeploymentIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tasks are an optional way to work with your latest certificate or trigger other actions before or after renewal.  的本地化字符串。
        /// </summary>
        public static string ManagedCertificates_Tasks_Intro {
            get {
                return ResourceManager.GetString("ManagedCertificates_Tasks_Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You can optionally add any number of tasks to run before the certificate request begins: 的本地化字符串。
        /// </summary>
        public static string ManagedCertificates_Tasks_PrerequestIntro {
            get {
                return ResourceManager.GetString("ManagedCertificates_Tasks_PrerequestIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There are unsaved changes to the selected site. Discard changes? 的本地化字符串。
        /// </summary>
        public static string ManagedCertificates_UnsavedWarning {
            get {
                return ResourceManager.GetString("ManagedCertificates_UnsavedWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 e.g. test.com, www.test.com or *.test.com 的本地化字符串。
        /// </summary>
        public static string ManagedCertificateSettings_AddDomainsHelpText {
            get {
                return ResourceManager.GetString("ManagedCertificateSettings_AddDomainsHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add domains to certificate: 的本地化字符串。
        /// </summary>
        public static string ManagedCertificateSettings_AddDomainsToCertificate {
            get {
                return ResourceManager.GetString("ManagedCertificateSettings_AddDomainsToCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto create/update IIS bindings (uses SNI) 的本地化字符串。
        /// </summary>
        public static string ManagedCertificateSettings_AutoUpdateBinding {
            get {
                return ResourceManager.GetString("ManagedCertificateSettings_AutoUpdateBinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Note: these setting only apply to new https bindings, existing bindings are only updated with the new certificate. Using a fixed IP for multiple certificates will cause a binding conflict on Windows, use with caution. 的本地化字符串。
        /// </summary>
        public static string ManagedCertificateSettings_BindingNote {
            get {
                return ResourceManager.GetString("ManagedCertificateSettings_BindingNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bind to Specific IP: 的本地化字符串。
        /// </summary>
        public static string ManagedCertificateSettings_BindIP {
            get {
                return ResourceManager.GetString("ManagedCertificateSettings_BindIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bind to Specific Port: 的本地化字符串。
        /// </summary>
        public static string ManagedCertificateSettings_BindPort {
            get {
                return ResourceManager.GetString("ManagedCertificateSettings_BindPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ... 的本地化字符串。
        /// </summary>
        public static string ManagedCertificateSettings_BrowseFolder {
            get {
                return ResourceManager.GetString("ManagedCertificateSettings_BrowseFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot check challenges if IIS is not available. 的本地化字符串。
        /// </summary>
        public static string ManagedCertificateSettings_CannotChallengeWithoutIIS {
            get {
                return ResourceManager.GetString("ManagedCertificateSettings_CannotChallengeWithoutIIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Certificate Revoked. 的本地化字符串。
        /// </summary>
        public static string ManagedCertificateSettings_Certificate_Revoked {
            get {
                return ResourceManager.GetString("ManagedCertificateSettings_Certificate_Revoked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Certificate Authorities are the organisations who can issue trusted certificates. You need to register an account under Settings for each (ACME) Certificate Authority you wish to use. 的本地化字符串。
        /// </summary>
        public static string ManagedCertificateSettings_CertificateAuthority_Intro {
            get {
                return ResourceManager.GetString("ManagedCertificateSettings_CertificateAuthority_Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Certificate Authority 的本地化字符串。
        /// </summary>
        public static string ManagedCertificateSettings_CertificateAuthority_Title {
            get {
                return ResourceManager.GetString("ManagedCertificateSettings_CertificateAuthority_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The certificate file for this item has not been created yet or the file has been deleted. 的本地化字符串。
        /// </summary>
        public static string ManagedCertificateSettings_CertificateNotReady {
            get {
                return ResourceManager.GetString("ManagedCertificateSettings_CertificateNotReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Certificate Path: [to be set] 的本地化字符串。
        /// </summary>
        public static string ManagedCertificateSettings_CertificatePathEmpty {
            get {
                return ResourceManager.GetString("ManagedCertificateSettings_CertificatePathEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WARNING: This certificate has been revoked. 的本地化字符串。
        /// </summary>
        public static string ManagedCertificateSettings_CertificateRevokeWarning {
            get {
                return ResourceManager.GetString("ManagedCertificateSettings_CertificateRevokeWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The {0} challenge is only available for IIS versions 8+. 的本地化字符串。
        /// </summary>
        public static string ManagedCertificateSettings_ChallengeNotAvailable {
            get {
                return ResourceManager.GetString("ManagedCertificateSettings_ChallengeNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Challenge Test Failed 的本地化字符串。
        /// </summary>
        public static string ManagedCertificateSettings_ChallengeTestFailed {
            get {
                return ResourceManager.GetString("ManagedCertificateSettings_ChallengeTestFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Challenge Type: 的本地化字符串。
        /// </summary>
        public static string ManagedCertificateSettings_ChallengeTypes {
            get {
                return ResourceManager.GetString("ManagedCertificateSettings_ChallengeTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Configuration Check Failed:
        ///{0} 的本地化字符串。
        /// </summary>
        public static string ManagedCertificateSettings_ConfigurationCheckFailed {
            get {
                return ResourceManager.GetString("ManagedCertificateSettings_ConfigurationCheckFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Configuration Checked OK 的本地化字符串。
        /// </summary>
        public static string ManagedCertificateSettings_ConfigurationCheckOk {
            get {
                return ResourceManager.GetString("ManagedCertificateSettings_ConfigurationCheckOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure you want to delete this item? Deleting the item will not affect IIS settings etc. 的本地化字符串。
        /// </summary>
        public static string ManagedCertificateSettings_ConfirmDelete {
            get {
                return ResourceManager.GetString("ManagedCertificateSettings_ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure you want to revoke this certificate? 的本地化字符串。
        /// </summary>
        public static string ManagedCertificateSettings_ConfirmRevokeCertificate {
            get {
                return ResourceManager.GetString("ManagedCertificateSettings_ConfirmRevokeCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New Managed Certificate 的本地化字符串。
        /// </summary>
        public static string ManagedCertificateSettings_DefaultTitle {
            get {
                return ResourceManager.GetString("ManagedCertificateSettings_DefaultTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Display Name: 的本地化字符串。
        /// </summary>
        public static string ManagedCertificateSettings_DisplayName {
            get {
                return ResourceManager.GetString("ManagedCertificateSettings_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Domain 的本地化字符串。
        /// </summary>
        public static string ManagedCertificateSettings_Domain {
            get {
                return ResourceManager.GetString("ManagedCertificateSettings_Domain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The following selected domains will be included as a single certificate request. The issuing Certificate Authority must be able to access all of these domains via port 80 (for HTTP challenges) or port 443 (for TLS-SNI challenges) for the certification process to work. 的本地化字符串。
        /// </summary>
        public static string ManagedCertificateSettings_DomainIncluded {
            get {
                return ResourceManager.GetString("ManagedCertificateSettings_DomainIncluded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select domains from existing hostname bindings on an website or add the domains manually. You can then select Request Certificate above or modify options as required. To specify a custom CSR see the Advanced tab. 的本地化字符串。
        /// </summary>
        public static string ManagedCertificateSettings_DomainsIntro {
            get {
                return ResourceManager.GetString("ManagedCertificateSettings_DomainsIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable Auto Renewal 的本地化字符串。
        /// </summary>
        public static string ManagedCertificateSettings_EnableAutoRenewal {
            get {
                return ResourceManager.GetString("ManagedCertificateSettings_EnableAutoRenewal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Note: To export this certificate use the Manage Computer Certificates option in Windows.  的本地化字符串。
        /// </summary>
        public static string ManagedCertificateSettings_ExportTip {
            get {
                return ResourceManager.GetString("ManagedCertificateSettings_ExportTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Body: 的本地化字符串。
        /// </summary>
        public static string ManagedCertificateSettings_HookBody {
            get {
                return ResourceManager.GetString("ManagedCertificateSettings_HookBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ContentType: 的本地化字符串。
        /// </summary>
        public static string ManagedCertificateSettings_HookContentType {
            get {
                return ResourceManager.GetString("ManagedCertificateSettings_HookContentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Method: 的本地化字符串。
        /// </summary>
        public static string ManagedCertificateSettings_HookMethod {
            get {
                return ResourceManager.GetString("ManagedCertificateSettings_HookMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The Method for the webhook must be set. 的本地化字符串。
        /// </summary>
        public static string ManagedCertificateSettings_HookMethodMustBeSet {
            get {
                return ResourceManager.GetString("ManagedCertificateSettings_HookMethodMustBeSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The Url for the webhook must be set to a valid Url. 的本地化字符串。
        /// </summary>
        public static string ManagedCertificateSettings_HookMustBeValidUrl {
            get {
                return ResourceManager.GetString("ManagedCertificateSettings_HookMustBeValidUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Webhook Trigger: 的本地化字符串。
        /// </summary>
        public static string ManagedCertificateSettings_HookTrigger {
            get {
                return ResourceManager.GetString("ManagedCertificateSettings_HookTrigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Url: 的本地化字符串。
        /// </summary>
        public static string ManagedCertificateSettings_HookUrl {
            get {
                return ResourceManager.GetString("ManagedCertificateSettings_HookUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Include 的本地化字符串。
        /// </summary>
        public static string ManagedCertificateSettings_Include {
            get {
                return ResourceManager.GetString("ManagedCertificateSettings_Include", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You are attempting to create an SNI binding that also has a specific bound IP address. It is recommended that SNI bindings use All Unassigned instead. Do you wish to continue saving? 的本地化字符串。
        /// </summary>
        public static string ManagedCertificateSettings_InvalidSNI {
            get {
                return ResourceManager.GetString("ManagedCertificateSettings_InvalidSNI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The log file for this item has not been created yet. 的本地化字符串。
        /// </summary>
        public static string ManagedCertificateSettings_LogNotCreated {
            get {
                return ResourceManager.GetString("ManagedCertificateSettings_LogNotCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A name is required for this item. 的本地化字符串。
        /// </summary>
        public static string ManagedCertificateSettings_NameRequired {
            get {
                return ResourceManager.GetString("ManagedCertificateSettings_NameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A Primary Domain must be included 的本地化字符串。
        /// </summary>
        public static string ManagedCertificateSettings_NeedPrimaryDomain {
            get {
                return ResourceManager.GetString("ManagedCertificateSettings_NeedPrimaryDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No changes were made, skipping save 的本地化字符串。
        /// </summary>
        public static string ManagedCertificateSettings_NoChanges {
            get {
                return ResourceManager.GetString("ManagedCertificateSettings_NoChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 At least one fully qualified hostname (e.g &apos;github.com&apos;) or wildcard (e.g. &apos;*.github.com) is required to create a certificate. 的本地化字符串。
        /// </summary>
        public static string ManagedCertificateSettings_NoHostNameBindingWarning {
            get {
                return ResourceManager.GetString("ManagedCertificateSettings_NoHostNameBindingWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Notify Primary Contact On Renewal Failure 的本地化字符串。
        /// </summary>
        public static string ManagedCertificateSettings_NotifyPrimaryContactOnRenewalFailure {
            get {
                return ResourceManager.GetString("ManagedCertificateSettings_NotifyPrimaryContactOnRenewalFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open Log File 的本地化字符串。
        /// </summary>
        public static string ManagedCertificateSettings_OpenLogFile {
            get {
                return ResourceManager.GetString("ManagedCertificateSettings_OpenLogFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Perform challenge response config checks 的本地化字符串。
        /// </summary>
        public static string ManagedCertificateSettings_PerformChallengeResponseConfigCheck {
            get {
                return ResourceManager.GetString("ManagedCertificateSettings_PerformChallengeResponseConfigCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Perform web application auto config 的本地化字符串。
        /// </summary>
        public static string ManagedCertificateSettings_PerformWebAppAutoConfig {
            get {
                return ResourceManager.GetString("ManagedCertificateSettings_PerformWebAppAutoConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pre-request PS Script: 的本地化字符串。
        /// </summary>
        public static string ManagedCertificateSettings_PerRequsetScript {
            get {
                return ResourceManager.GetString("ManagedCertificateSettings_PerRequsetScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Post-request PS Script: 的本地化字符串。
        /// </summary>
        public static string ManagedCertificateSettings_PostRequestScript {
            get {
                return ResourceManager.GetString("ManagedCertificateSettings_PostRequestScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Primary 的本地化字符串。
        /// </summary>
        public static string ManagedCertificateSettings_Primary {
            get {
                return ResourceManager.GetString("ManagedCertificateSettings_Primary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Re-apply Certificate to Bindings 的本地化字符串。
        /// </summary>
        public static string ManagedCertificateSettings_ReapplyCertificate {
            get {
                return ResourceManager.GetString("ManagedCertificateSettings_ReapplyCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Request Certificate 的本地化字符串。
        /// </summary>
        public static string ManagedCertificateSettings_RequestCertificate {
            get {
                return ResourceManager.GetString("ManagedCertificateSettings_RequestCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Revoke Certificate 的本地化字符串。
        /// </summary>
        public static string ManagedCertificateSettings_RevokeCertificate {
            get {
                return ResourceManager.GetString("ManagedCertificateSettings_RevokeCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error Revoking Certificate:
        ///{0} 的本地化字符串。
        /// </summary>
        public static string ManagedCertificateSettings_RevokeCertificateError {
            get {
                return ResourceManager.GetString("ManagedCertificateSettings_RevokeCertificateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Domains and Subdomains to include: 的本地化字符串。
        /// </summary>
        public static string ManagedCertificateSettings_SelectDomain {
            get {
                return ResourceManager.GetString("ManagedCertificateSettings_SelectDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select None 的本地化字符串。
        /// </summary>
        public static string ManagedCertificateSettings_SelectNone {
            get {
                return ResourceManager.GetString("ManagedCertificateSettings_SelectNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select Site (optional): 的本地化字符串。
        /// </summary>
        public static string ManagedCertificateSettings_SelectWebsite {
            get {
                return ResourceManager.GetString("ManagedCertificateSettings_SelectWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select the site to create a certificate for. 的本地化字符串。
        /// </summary>
        public static string ManagedCertificateSettings_SelectWebsiteOrCert {
            get {
                return ResourceManager.GetString("ManagedCertificateSettings_SelectWebsiteOrCert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Options 的本地化字符串。
        /// </summary>
        public static string ManagedCertificateSettings_Tab_Options {
            get {
                return ResourceManager.GetString("ManagedCertificateSettings_Tab_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use SNI (IIS 8+): 的本地化字符串。
        /// </summary>
        public static string ManagedCertificateSettings_UseSNI {
            get {
                return ResourceManager.GetString("ManagedCertificateSettings_UseSNI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use specific IP/Port bindings 的本地化字符串。
        /// </summary>
        public static string ManagedCertificateSettings_UseSpecificBinding {
            get {
                return ResourceManager.GetString("ManagedCertificateSettings_UseSpecificBinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 View Certificate 的本地化字符串。
        /// </summary>
        public static string ManagedCertificateSettings_ViewCertificate {
            get {
                return ResourceManager.GetString("ManagedCertificateSettings_ViewCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Webhook request error: {0} 的本地化字符串。
        /// </summary>
        public static string ManagedCertificateSettings_WebhookRequestError {
            get {
                return ResourceManager.GetString("ManagedCertificateSettings_WebhookRequestError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Webhook request {0}: HTTP {1} 的本地化字符串。
        /// </summary>
        public static string ManagedCertificateSettings_WebhookRequestResult {
            get {
                return ResourceManager.GetString("ManagedCertificateSettings_WebhookRequestResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Webhook Test 的本地化字符串。
        /// </summary>
        public static string ManagedCertificateSettings_WebhookTest {
            get {
                return ResourceManager.GetString("ManagedCertificateSettings_WebhookTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Webhook Test Failed 的本地化字符串。
        /// </summary>
        public static string ManagedCertificateSettings_WebhookTestFailed {
            get {
                return ResourceManager.GetString("ManagedCertificateSettings_WebhookTestFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Site Root Directory 的本地化字符串。
        /// </summary>
        public static string ManagedCertificateSettings_WebsiteRoot {
            get {
                return ResourceManager.GetString("ManagedCertificateSettings_WebsiteRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Refresh 的本地化字符串。
        /// </summary>
        public static string ManagedCertificatesSettings_RefreshDomains {
            get {
                return ResourceManager.GetString("ManagedCertificatesSettings_RefreshDomains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New Certificate 的本地化字符串。
        /// </summary>
        public static string New_Certificate {
            get {
                return ResourceManager.GetString("New_Certificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There was a problem registering with the Certificate Authority using this email address. Check the email address is valid and that this computer has an open connection to the internet (outgoing https is required for API calls). 的本地化字符串。
        /// </summary>
        public static string New_Contact_EmailError {
            get {
                return ResourceManager.GetString("New_Contact_EmailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 To proceed, confirm that you agree to the current terms and conditions for this Certificate Authority. 的本地化字符串。
        /// </summary>
        public static string New_Contact_NeedAgree {
            get {
                return ResourceManager.GetString("New_Contact_NeedAgree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 To request certificates you need to register with each of the Certificate Authorities that you want to use. 的本地化字符串。
        /// </summary>
        public static string New_Contact_Tip1 {
            get {
                return ResourceManager.GetString("New_Contact_Tip1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The email address provided may be used to notify you of upcoming certificate renewals if required. Invalid email addresses will be rejected by the Certificate Authority. 的本地化字符串。
        /// </summary>
        public static string New_Contact_Tip2 {
            get {
                return ResourceManager.GetString("New_Contact_Tip2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OK 的本地化字符串。
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Password 的本地化字符串。
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Preferred Certificate Authority 的本地化字符串。
        /// </summary>
        public static string PreferredCertificateAuthority {
            get {
                return ResourceManager.GetString("PreferredCertificateAuthority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There are no requests currently in progress. 的本地化字符串。
        /// </summary>
        public static string ProgressMonitor_NoProgress {
            get {
                return ResourceManager.GetString("ProgressMonitor_NoProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Register Contact 的本地化字符串。
        /// </summary>
        public static string Register_Contact {
            get {
                return ResourceManager.GetString("Register_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Registration 的本地化字符串。
        /// </summary>
        public static string Registration {
            get {
                return ResourceManager.GetString("Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There was a problem trying to validate your license key. Please try again or contact support. 的本地化字符串。
        /// </summary>
        public static string Registration_KeyValidationError {
            get {
                return ResourceManager.GetString("Registration_KeyValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter the email address you used when registering your key. 的本地化字符串。
        /// </summary>
        public static string Registration_NeedEmail {
            get {
                return ResourceManager.GetString("Registration_NeedEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter your license key. 的本地化字符串。
        /// </summary>
        public static string Registration_NeedKey {
            get {
                return ResourceManager.GetString("Registration_NeedKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There was a problem beginning the license validation process. 的本地化字符串。
        /// </summary>
        public static string Registration_UnableToVerify {
            get {
                return ResourceManager.GetString("Registration_UnableToVerify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Registered Email Address 的本地化字符串。
        /// </summary>
        public static string RegistrationEmailAddress {
            get {
                return ResourceManager.GetString("RegistrationEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Renew All 的本地化字符串。
        /// </summary>
        public static string Renew_All {
            get {
                return ResourceManager.GetString("Renew_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save 的本地化字符串。
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save Changes 的本地化字符串。
        /// </summary>
        public static string SaveChanges {
            get {
                return ResourceManager.GetString("SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save Error 的本地化字符串。
        /// </summary>
        public static string SaveError {
            get {
                return ResourceManager.GetString("SaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The auto renewal task is already configured. If required you can change the admin user account used to execute the task. 的本地化字符串。
        /// </summary>
        public static string ScheduledTaskConfig_AlreadyConfiged {
            get {
                return ResourceManager.GetString("ScheduledTaskConfig_AlreadyConfiged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to create scheduled task with given credentials 的本地化字符串。
        /// </summary>
        public static string ScheduledTaskConfig_FailedToCreateTask {
            get {
                return ResourceManager.GetString("ScheduledTaskConfig_FailedToCreateTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please provide the username and password for an admin level user. 的本地化字符串。
        /// </summary>
        public static string ScheduledTaskConfig_PleaseProvideCredential {
            get {
                return ResourceManager.GetString("ScheduledTaskConfig_PleaseProvideCredential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Scheduled task created 的本地化字符串。
        /// </summary>
        public static string ScheduledTaskConfig_TaskCreated {
            get {
                return ResourceManager.GetString("ScheduledTaskConfig_TaskCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 To perform auto renewal of certificates, a task will be created in the Windows Task Scheduler. This task needs to run as an Admin level user in order to do certificate management and IIS management tasks. 的本地化字符串。
        /// </summary>
        public static string ScheduledTaskConfig_Tip {
            get {
                return ResourceManager.GetString("ScheduledTaskConfig_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use Background Service (runs as Local System) 的本地化字符串。
        /// </summary>
        public static string ScheduledTaskConfig_UseBackgroundService {
            get {
                return ResourceManager.GetString("ScheduledTaskConfig_UseBackgroundService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Username (DOMAIN\User) 的本地化字符串。
        /// </summary>
        public static string ScheduledTaskConfig_UserNameLabel {
            get {
                return ResourceManager.GetString("ScheduledTaskConfig_UserNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use a Scheduled Task (runs as specified user) 的本地化字符串。
        /// </summary>
        public static string ScheduledTaskConfig_UseScheduledTask {
            get {
                return ResourceManager.GetString("ScheduledTaskConfig_UseScheduledTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Configure Auto Renewal 的本地化字符串。
        /// </summary>
        public static string ScheduledTaskConfig_WindowTitle {
            get {
                return ResourceManager.GetString("ScheduledTaskConfig_WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select All 的本地化字符串。
        /// </summary>
        public static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Send 的本地化字符串。
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Send Feedback 的本地化字符串。
        /// </summary>
        public static string Send_Feedback {
            get {
                return ResourceManager.GetString("Send_Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Your Email Address (optional): 的本地化字符串。
        /// </summary>
        public static string Send_Feedback_Email {
            get {
                return ResourceManager.GetString("Send_Feedback_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sorry, there was a problem submitting your feedback. 的本地化字符串。
        /// </summary>
        public static string Send_Feedback_Error {
            get {
                return ResourceManager.GetString("Send_Feedback_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Oops, something went wrong. Please tell us about it. 的本地化字符串。
        /// </summary>
        public static string Send_Feedback_Exception {
            get {
                return ResourceManager.GetString("Send_Feedback_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Do you have any suggestions? 的本地化字符串。
        /// </summary>
        public static string Send_Feedback_Quest {
            get {
                return ResourceManager.GetString("Send_Feedback_Quest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Thanks, your feedback has now been submitted. 的本地化字符串。
        /// </summary>
        public static string Send_Feedback_Success {
            get {
                return ResourceManager.GetString("Send_Feedback_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Thanks for submitting feedback to our developers. Please email support@certifytheweb.com if you have a question. 的本地化字符串。
        /// </summary>
        public static string Send_Feedback_Tip {
            get {
                return ResourceManager.GetString("Send_Feedback_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings 的本地化字符串。
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto Renewal Interval (Days) 的本地化字符串。
        /// </summary>
        public static string Settings_AutoRenewalInterval {
            get {
                return ResourceManager.GetString("Settings_AutoRenewalInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Maximum Auto Renewal Requests Per Session (0 = Unlimited) 的本地化字符串。
        /// </summary>
        public static string Settings_AutoRenewalRequestLimit {
            get {
                return ResourceManager.GetString("Settings_AutoRenewalRequestLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Check for updates automatically 的本地化字符串。
        /// </summary>
        public static string Settings_CheckUpdates {
            get {
                return ResourceManager.GetString("Settings_CheckUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable Certificate Cleanup 的本地化字符串。
        /// </summary>
        public static string Settings_EnableCertificateCleanup {
            get {
                return ResourceManager.GetString("Settings_EnableCertificateCleanup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable DNS Validation Checks (Resolution, CAA, DNSSEC) 的本地化字符串。
        /// </summary>
        public static string Settings_EnableDnsValidation {
            get {
                return ResourceManager.GetString("Settings_EnableDnsValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable Encrypted File System (EFS) for sensitive files. This option does not work on all versions of Windows. 的本地化字符串。
        /// </summary>
        public static string Settings_EnableEFS {
            get {
                return ResourceManager.GetString("Settings_EnableEFS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable Http Challenge Server 的本地化字符串。
        /// </summary>
        public static string Settings_EnableHttpChallengeServer {
            get {
                return ResourceManager.GetString("Settings_EnableHttpChallengeServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable Proxy API for Domain Config Checks 的本地化字符串。
        /// </summary>
        public static string Settings_EnableProxyApiForDomainConfig {
            get {
                return ResourceManager.GetString("Settings_EnableProxyApiForDomainConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable Status Reports to Dashboard 的本地化字符串。
        /// </summary>
        public static string Settings_EnableStatusReporting {
            get {
                return ResourceManager.GetString("Settings_EnableStatusReporting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable App Telemetry (feature usage reporting) 的本地化字符串。
        /// </summary>
        public static string Settings_EnableTelemetry {
            get {
                return ResourceManager.GetString("Settings_EnableTelemetry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ignore stopped IIS sites for new certificates and renewals 的本地化字符串。
        /// </summary>
        public static string Settings_IgnoreStoppedSites {
            get {
                return ResourceManager.GetString("Settings_IgnoreStoppedSites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Primary Contact: 的本地化字符串。
        /// </summary>
        public static string Settings_PrimaryContact {
            get {
                return ResourceManager.GetString("Settings_PrimaryContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 succeeded 的本地化字符串。
        /// </summary>
        public static string succeed {
            get {
                return ResourceManager.GetString("succeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Test 的本地化字符串。
        /// </summary>
        public static string Test {
            get {
                return ResourceManager.GetString("Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update Available 的本地化字符串。
        /// </summary>
        public static string Update_Available {
            get {
                return ResourceManager.GetString("Update_Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sorry, the update could not be downloaded. Please try again later. 的本地化字符串。
        /// </summary>
        public static string Update_DownloadFailed {
            get {
                return ResourceManager.GetString("Update_DownloadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Would you like to automatically download the update? You will be notified when it is ready to apply. 的本地化字符串。
        /// </summary>
        public static string Update_DownloadNow {
            get {
                return ResourceManager.GetString("Update_DownloadNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The current app version requires an essential update to ensure continued operation. Please update immediately. Close app now? 的本地化字符串。
        /// </summary>
        public static string Update_MandatoryUpdateQuit {
            get {
                return ResourceManager.GetString("Update_MandatoryUpdateQuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A new update is ready to apply. Would you like to install it now? 的本地化字符串。
        /// </summary>
        public static string Update_ReadyToApply {
            get {
                return ResourceManager.GetString("Update_ReadyToApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You are using the latest version. 的本地化字符串。
        /// </summary>
        public static string UpdateCheckLatestVersion {
            get {
                return ResourceManager.GetString("UpdateCheckLatestVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Validate Key 的本地化字符串。
        /// </summary>
        public static string ValidateKey {
            get {
                return ResourceManager.GetString("ValidateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Yes, I Agree 的本地化字符串。
        /// </summary>
        public static string Yes_I_Agree {
            get {
                return ResourceManager.GetString("Yes_I_Agree", resourceCulture);
            }
        }
    }
}
