import { OpenApiGenerationClient } from './AutoGeneratedCode/OpenApiTemplateGeneration'
export * from './AutoGeneratedCode/OpenApiTemplateGeneration'

export class OpenApiClient extends OpenApiGenerationClient { }
