//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.0.7.0 (NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming

import { type AxiosRequestConfig, type AxiosInstance, type AxiosResponse } from 'axios'
import { service as defaultRequest} from '@/utils/request'

export class OpenApiGenerationClient {
    private httpRequest: <T = any>(config: AxiosRequestConfig) => Promise<AxiosResponse<T>>;
    private baseUrl: string;

    constructor(baseUrl?: string, requestInstance?: AxiosInstance) {
        this.httpRequest = requestInstance ?? defaultRequest;
        this.baseUrl = baseUrl !== undefined && baseUrl !== null ? baseUrl : "http://172.29.0.12:7005";
    }

    /**
     * @return OK
     */
    RequestCertifica = async (axiosConfig?: AxiosRequestConfig) => {
        let url_ = "/api/AcmeCertificate/RequestCertifica";
        url_ = url_.replace(/[?&]$/, "");

        let config: AxiosRequestConfig = {
            ...axiosConfig,
            url: url_,
            baseURL: this.baseUrl,
            method: "POST",
            headers: {
            }
        };

        const response = await this.httpRequest<void>(config);

    }

    /**
     * @return OK
     */
    GetCertificateAuthorities = async (axiosConfig?: AxiosRequestConfig) => {
        let url_ = "/api/AcmeCertificate/GetCertificateAuthorities";
        url_ = url_.replace(/[?&]$/, "");

        let config: AxiosRequestConfig = {
            ...axiosConfig,
            url: url_,
            baseURL: this.baseUrl,
            method: "GET",
            headers: {
                "Accept": "text/plain"
            }
        };

        const response = await this.httpRequest<CertificateAuthority[]>(config);
        return response?.data;

    }
}
//#region 请求对象
//#endregion

//#region CertificateAuthority 模型
export class CertificateAuthority {
    id?: string | undefined;
    apiType?: string;
    supportedFeatures?: string[];
    title?: string;
    description?: string;
    websiteUrl?: string;
    privacyPolicyUrl?: string;
    termsAndConditionsUrl?: string;
    statusUrl?: string;
    productionAPIEndpoint?: string;
    stagingAPIEndpoint?: string;
    defaultPreferredChain?: string;
    isEnabled?: boolean;
    isCustom?: boolean;
    sanLimit?: number;
    standardExpiryDays?: number;
    requiresEmailAddress?: boolean;
    requiresExternalAccountBinding?: boolean;
    allowUntrustedTls?: boolean;
    allowInternalHostnames?: boolean;
    supportsCachedValidations?: boolean;
    eabInstructions?: string;
    supportedKeyTypes?: string[];
    disabledIntermediates?: string[];
    trustedRoots?: { [key: string]: string; };
    intermediates?: { [key: string]: string; };
    [key: string]: any;
}

export const CertificateAuthorityColumns = {
    Id: { dataIndex: 'id', title: 'id' },
    ApiType: { dataIndex: 'apiType', title: 'apiType' },
    SupportedFeatures: { dataIndex: 'supportedFeatures', title: 'supportedFeatures' },
    Title: { dataIndex: 'title', title: 'title' },
    Description: { dataIndex: 'description', title: 'description' },
    WebsiteUrl: { dataIndex: 'websiteUrl', title: 'websiteUrl' },
    PrivacyPolicyUrl: { dataIndex: 'privacyPolicyUrl', title: 'privacyPolicyUrl' },
    TermsAndConditionsUrl: { dataIndex: 'termsAndConditionsUrl', title: 'termsAndConditionsUrl' },
    StatusUrl: { dataIndex: 'statusUrl', title: 'statusUrl' },
    ProductionAPIEndpoint: { dataIndex: 'productionAPIEndpoint', title: 'productionAPIEndpoint' },
    StagingAPIEndpoint: { dataIndex: 'stagingAPIEndpoint', title: 'stagingAPIEndpoint' },
    DefaultPreferredChain: { dataIndex: 'defaultPreferredChain', title: 'defaultPreferredChain' },
    IsEnabled: { dataIndex: 'isEnabled', title: 'isEnabled' },
    IsCustom: { dataIndex: 'isCustom', title: 'isCustom' },
    SanLimit: { dataIndex: 'sanLimit', title: 'sanLimit' },
    StandardExpiryDays: { dataIndex: 'standardExpiryDays', title: 'standardExpiryDays' },
    RequiresEmailAddress: { dataIndex: 'requiresEmailAddress', title: 'requiresEmailAddress' },
    RequiresExternalAccountBinding: { dataIndex: 'requiresExternalAccountBinding', title: 'requiresExternalAccountBinding' },
    AllowUntrustedTls: { dataIndex: 'allowUntrustedTls', title: 'allowUntrustedTls' },
    AllowInternalHostnames: { dataIndex: 'allowInternalHostnames', title: 'allowInternalHostnames' },
    SupportsCachedValidations: { dataIndex: 'supportsCachedValidations', title: 'supportsCachedValidations' },
    EabInstructions: { dataIndex: 'eabInstructions', title: 'eabInstructions' },
    SupportedKeyTypes: { dataIndex: 'supportedKeyTypes', title: 'supportedKeyTypes' },
    DisabledIntermediates: { dataIndex: 'disabledIntermediates', title: 'disabledIntermediates' },
    TrustedRoots: { dataIndex: 'trustedRoots', title: 'trustedRoots' },
    Intermediates: { dataIndex: 'intermediates', title: 'intermediates' },
};

/* 
<a-form-model ref="formRef" :model="formState.ruleForm" :labelCol="{ xs: { span: 24 }, sm: { span: 5 } }" :wrapperCol="{ xs: { span: 24 }, sm: { span: 15 } }">
    <a-form-model-item label="id" prop="id" :rules="{ required: true, message: `请输入 id！`, trigger: 'blur' }" has-feedback>
        <a-input placeholder="请输入 id" v-model="formState.ruleForm.id" allowClear />
        <!-- 
        // 文本
        {{ id ?? "-" }}
        // 文本域
        <a-textarea placeholder="请输入 id" v-model="formState.ruleForm.id" allowClear show-count :rows="4" />
        // 日期选择框
        <a-date-picker placeholder="请选择 id" v-model="formState.ruleForm.id" allowClear style="width: 100%;" />
        // 下拉选择框
        <a-select placeholder="请选择 id" v-model="formState.ruleForm.id" allowClear>
            <a-select-option value="A" key="A">test</a-select-option>
            <a-select-option value="B" key="B">test</a-select-option>
        </a-select>
        // 单选框
        <a-radio-group v-model="formState.ruleForm.id">
            <a-radio-button value="A">A</a-radio-button>
            <a-radio-button value="B">B</a-radio-button>
        </a-radio-group>
        // 复选框
        <a-checkbox-group v-model="formState.ruleForm.id">
            <a-checkbox value="A">A</a-checkbox>
            <a-checkbox value="B">B</a-checkbox>
        </a-checkbox-group>
        // 开关
        <a-switch checked-children="开" un-checked-children="关" v-model="formState.ruleForm.id" />
        // 评分
        <a-rate v-model="formState.ruleForm.id" allow-half />
        -->
    </a-form-model-item>
    <a-form-model-item label="apiType" prop="apiType" :rules="{ required: true, message: `请输入 apiType！`, trigger: 'blur' }" has-feedback>
        <a-input placeholder="请输入 apiType" v-model="formState.ruleForm.apiType" allowClear />
        <!-- 
        // 文本
        {{ apiType ?? "-" }}
        // 文本域
        <a-textarea placeholder="请输入 apiType" v-model="formState.ruleForm.apiType" allowClear show-count :rows="4" />
        // 日期选择框
        <a-date-picker placeholder="请选择 apiType" v-model="formState.ruleForm.apiType" allowClear style="width: 100%;" />
        // 下拉选择框
        <a-select placeholder="请选择 apiType" v-model="formState.ruleForm.apiType" allowClear>
            <a-select-option value="A" key="A">test</a-select-option>
            <a-select-option value="B" key="B">test</a-select-option>
        </a-select>
        // 单选框
        <a-radio-group v-model="formState.ruleForm.apiType">
            <a-radio-button value="A">A</a-radio-button>
            <a-radio-button value="B">B</a-radio-button>
        </a-radio-group>
        // 复选框
        <a-checkbox-group v-model="formState.ruleForm.apiType">
            <a-checkbox value="A">A</a-checkbox>
            <a-checkbox value="B">B</a-checkbox>
        </a-checkbox-group>
        // 开关
        <a-switch checked-children="开" un-checked-children="关" v-model="formState.ruleForm.apiType" />
        // 评分
        <a-rate v-model="formState.ruleForm.apiType" allow-half />
        -->
    </a-form-model-item>
    <a-form-model-item label="supportedFeatures" prop="supportedFeatures" :rules="{ required: true, message: `请输入 supportedFeatures！`, trigger: 'blur' }" has-feedback>
        <a-input placeholder="请输入 supportedFeatures" v-model="formState.ruleForm.supportedFeatures" allowClear />
        <!-- 
        // 文本
        {{ supportedFeatures ?? "-" }}
        // 文本域
        <a-textarea placeholder="请输入 supportedFeatures" v-model="formState.ruleForm.supportedFeatures" allowClear show-count :rows="4" />
        // 日期选择框
        <a-date-picker placeholder="请选择 supportedFeatures" v-model="formState.ruleForm.supportedFeatures" allowClear style="width: 100%;" />
        // 下拉选择框
        <a-select placeholder="请选择 supportedFeatures" v-model="formState.ruleForm.supportedFeatures" allowClear>
            <a-select-option value="A" key="A">test</a-select-option>
            <a-select-option value="B" key="B">test</a-select-option>
        </a-select>
        // 单选框
        <a-radio-group v-model="formState.ruleForm.supportedFeatures">
            <a-radio-button value="A">A</a-radio-button>
            <a-radio-button value="B">B</a-radio-button>
        </a-radio-group>
        // 复选框
        <a-checkbox-group v-model="formState.ruleForm.supportedFeatures">
            <a-checkbox value="A">A</a-checkbox>
            <a-checkbox value="B">B</a-checkbox>
        </a-checkbox-group>
        // 开关
        <a-switch checked-children="开" un-checked-children="关" v-model="formState.ruleForm.supportedFeatures" />
        // 评分
        <a-rate v-model="formState.ruleForm.supportedFeatures" allow-half />
        -->
    </a-form-model-item>
    <a-form-model-item label="title" prop="title" :rules="{ required: true, message: `请输入 title！`, trigger: 'blur' }" has-feedback>
        <a-input placeholder="请输入 title" v-model="formState.ruleForm.title" allowClear />
        <!-- 
        // 文本
        {{ title ?? "-" }}
        // 文本域
        <a-textarea placeholder="请输入 title" v-model="formState.ruleForm.title" allowClear show-count :rows="4" />
        // 日期选择框
        <a-date-picker placeholder="请选择 title" v-model="formState.ruleForm.title" allowClear style="width: 100%;" />
        // 下拉选择框
        <a-select placeholder="请选择 title" v-model="formState.ruleForm.title" allowClear>
            <a-select-option value="A" key="A">test</a-select-option>
            <a-select-option value="B" key="B">test</a-select-option>
        </a-select>
        // 单选框
        <a-radio-group v-model="formState.ruleForm.title">
            <a-radio-button value="A">A</a-radio-button>
            <a-radio-button value="B">B</a-radio-button>
        </a-radio-group>
        // 复选框
        <a-checkbox-group v-model="formState.ruleForm.title">
            <a-checkbox value="A">A</a-checkbox>
            <a-checkbox value="B">B</a-checkbox>
        </a-checkbox-group>
        // 开关
        <a-switch checked-children="开" un-checked-children="关" v-model="formState.ruleForm.title" />
        // 评分
        <a-rate v-model="formState.ruleForm.title" allow-half />
        -->
    </a-form-model-item>
    <a-form-model-item label="description" prop="description" :rules="{ required: true, message: `请输入 description！`, trigger: 'blur' }" has-feedback>
        <a-input placeholder="请输入 description" v-model="formState.ruleForm.description" allowClear />
        <!-- 
        // 文本
        {{ description ?? "-" }}
        // 文本域
        <a-textarea placeholder="请输入 description" v-model="formState.ruleForm.description" allowClear show-count :rows="4" />
        // 日期选择框
        <a-date-picker placeholder="请选择 description" v-model="formState.ruleForm.description" allowClear style="width: 100%;" />
        // 下拉选择框
        <a-select placeholder="请选择 description" v-model="formState.ruleForm.description" allowClear>
            <a-select-option value="A" key="A">test</a-select-option>
            <a-select-option value="B" key="B">test</a-select-option>
        </a-select>
        // 单选框
        <a-radio-group v-model="formState.ruleForm.description">
            <a-radio-button value="A">A</a-radio-button>
            <a-radio-button value="B">B</a-radio-button>
        </a-radio-group>
        // 复选框
        <a-checkbox-group v-model="formState.ruleForm.description">
            <a-checkbox value="A">A</a-checkbox>
            <a-checkbox value="B">B</a-checkbox>
        </a-checkbox-group>
        // 开关
        <a-switch checked-children="开" un-checked-children="关" v-model="formState.ruleForm.description" />
        // 评分
        <a-rate v-model="formState.ruleForm.description" allow-half />
        -->
    </a-form-model-item>
    <a-form-model-item label="websiteUrl" prop="websiteUrl" :rules="{ required: true, message: `请输入 websiteUrl！`, trigger: 'blur' }" has-feedback>
        <a-input placeholder="请输入 websiteUrl" v-model="formState.ruleForm.websiteUrl" allowClear />
        <!-- 
        // 文本
        {{ websiteUrl ?? "-" }}
        // 文本域
        <a-textarea placeholder="请输入 websiteUrl" v-model="formState.ruleForm.websiteUrl" allowClear show-count :rows="4" />
        // 日期选择框
        <a-date-picker placeholder="请选择 websiteUrl" v-model="formState.ruleForm.websiteUrl" allowClear style="width: 100%;" />
        // 下拉选择框
        <a-select placeholder="请选择 websiteUrl" v-model="formState.ruleForm.websiteUrl" allowClear>
            <a-select-option value="A" key="A">test</a-select-option>
            <a-select-option value="B" key="B">test</a-select-option>
        </a-select>
        // 单选框
        <a-radio-group v-model="formState.ruleForm.websiteUrl">
            <a-radio-button value="A">A</a-radio-button>
            <a-radio-button value="B">B</a-radio-button>
        </a-radio-group>
        // 复选框
        <a-checkbox-group v-model="formState.ruleForm.websiteUrl">
            <a-checkbox value="A">A</a-checkbox>
            <a-checkbox value="B">B</a-checkbox>
        </a-checkbox-group>
        // 开关
        <a-switch checked-children="开" un-checked-children="关" v-model="formState.ruleForm.websiteUrl" />
        // 评分
        <a-rate v-model="formState.ruleForm.websiteUrl" allow-half />
        -->
    </a-form-model-item>
    <a-form-model-item label="privacyPolicyUrl" prop="privacyPolicyUrl" :rules="{ required: true, message: `请输入 privacyPolicyUrl！`, trigger: 'blur' }" has-feedback>
        <a-input placeholder="请输入 privacyPolicyUrl" v-model="formState.ruleForm.privacyPolicyUrl" allowClear />
        <!-- 
        // 文本
        {{ privacyPolicyUrl ?? "-" }}
        // 文本域
        <a-textarea placeholder="请输入 privacyPolicyUrl" v-model="formState.ruleForm.privacyPolicyUrl" allowClear show-count :rows="4" />
        // 日期选择框
        <a-date-picker placeholder="请选择 privacyPolicyUrl" v-model="formState.ruleForm.privacyPolicyUrl" allowClear style="width: 100%;" />
        // 下拉选择框
        <a-select placeholder="请选择 privacyPolicyUrl" v-model="formState.ruleForm.privacyPolicyUrl" allowClear>
            <a-select-option value="A" key="A">test</a-select-option>
            <a-select-option value="B" key="B">test</a-select-option>
        </a-select>
        // 单选框
        <a-radio-group v-model="formState.ruleForm.privacyPolicyUrl">
            <a-radio-button value="A">A</a-radio-button>
            <a-radio-button value="B">B</a-radio-button>
        </a-radio-group>
        // 复选框
        <a-checkbox-group v-model="formState.ruleForm.privacyPolicyUrl">
            <a-checkbox value="A">A</a-checkbox>
            <a-checkbox value="B">B</a-checkbox>
        </a-checkbox-group>
        // 开关
        <a-switch checked-children="开" un-checked-children="关" v-model="formState.ruleForm.privacyPolicyUrl" />
        // 评分
        <a-rate v-model="formState.ruleForm.privacyPolicyUrl" allow-half />
        -->
    </a-form-model-item>
    <a-form-model-item label="termsAndConditionsUrl" prop="termsAndConditionsUrl" :rules="{ required: true, message: `请输入 termsAndConditionsUrl！`, trigger: 'blur' }" has-feedback>
        <a-input placeholder="请输入 termsAndConditionsUrl" v-model="formState.ruleForm.termsAndConditionsUrl" allowClear />
        <!-- 
        // 文本
        {{ termsAndConditionsUrl ?? "-" }}
        // 文本域
        <a-textarea placeholder="请输入 termsAndConditionsUrl" v-model="formState.ruleForm.termsAndConditionsUrl" allowClear show-count :rows="4" />
        // 日期选择框
        <a-date-picker placeholder="请选择 termsAndConditionsUrl" v-model="formState.ruleForm.termsAndConditionsUrl" allowClear style="width: 100%;" />
        // 下拉选择框
        <a-select placeholder="请选择 termsAndConditionsUrl" v-model="formState.ruleForm.termsAndConditionsUrl" allowClear>
            <a-select-option value="A" key="A">test</a-select-option>
            <a-select-option value="B" key="B">test</a-select-option>
        </a-select>
        // 单选框
        <a-radio-group v-model="formState.ruleForm.termsAndConditionsUrl">
            <a-radio-button value="A">A</a-radio-button>
            <a-radio-button value="B">B</a-radio-button>
        </a-radio-group>
        // 复选框
        <a-checkbox-group v-model="formState.ruleForm.termsAndConditionsUrl">
            <a-checkbox value="A">A</a-checkbox>
            <a-checkbox value="B">B</a-checkbox>
        </a-checkbox-group>
        // 开关
        <a-switch checked-children="开" un-checked-children="关" v-model="formState.ruleForm.termsAndConditionsUrl" />
        // 评分
        <a-rate v-model="formState.ruleForm.termsAndConditionsUrl" allow-half />
        -->
    </a-form-model-item>
    <a-form-model-item label="statusUrl" prop="statusUrl" :rules="{ required: true, message: `请输入 statusUrl！`, trigger: 'blur' }" has-feedback>
        <a-input placeholder="请输入 statusUrl" v-model="formState.ruleForm.statusUrl" allowClear />
        <!-- 
        // 文本
        {{ statusUrl ?? "-" }}
        // 文本域
        <a-textarea placeholder="请输入 statusUrl" v-model="formState.ruleForm.statusUrl" allowClear show-count :rows="4" />
        // 日期选择框
        <a-date-picker placeholder="请选择 statusUrl" v-model="formState.ruleForm.statusUrl" allowClear style="width: 100%;" />
        // 下拉选择框
        <a-select placeholder="请选择 statusUrl" v-model="formState.ruleForm.statusUrl" allowClear>
            <a-select-option value="A" key="A">test</a-select-option>
            <a-select-option value="B" key="B">test</a-select-option>
        </a-select>
        // 单选框
        <a-radio-group v-model="formState.ruleForm.statusUrl">
            <a-radio-button value="A">A</a-radio-button>
            <a-radio-button value="B">B</a-radio-button>
        </a-radio-group>
        // 复选框
        <a-checkbox-group v-model="formState.ruleForm.statusUrl">
            <a-checkbox value="A">A</a-checkbox>
            <a-checkbox value="B">B</a-checkbox>
        </a-checkbox-group>
        // 开关
        <a-switch checked-children="开" un-checked-children="关" v-model="formState.ruleForm.statusUrl" />
        // 评分
        <a-rate v-model="formState.ruleForm.statusUrl" allow-half />
        -->
    </a-form-model-item>
    <a-form-model-item label="productionAPIEndpoint" prop="productionAPIEndpoint" :rules="{ required: true, message: `请输入 productionAPIEndpoint！`, trigger: 'blur' }" has-feedback>
        <a-input placeholder="请输入 productionAPIEndpoint" v-model="formState.ruleForm.productionAPIEndpoint" allowClear />
        <!-- 
        // 文本
        {{ productionAPIEndpoint ?? "-" }}
        // 文本域
        <a-textarea placeholder="请输入 productionAPIEndpoint" v-model="formState.ruleForm.productionAPIEndpoint" allowClear show-count :rows="4" />
        // 日期选择框
        <a-date-picker placeholder="请选择 productionAPIEndpoint" v-model="formState.ruleForm.productionAPIEndpoint" allowClear style="width: 100%;" />
        // 下拉选择框
        <a-select placeholder="请选择 productionAPIEndpoint" v-model="formState.ruleForm.productionAPIEndpoint" allowClear>
            <a-select-option value="A" key="A">test</a-select-option>
            <a-select-option value="B" key="B">test</a-select-option>
        </a-select>
        // 单选框
        <a-radio-group v-model="formState.ruleForm.productionAPIEndpoint">
            <a-radio-button value="A">A</a-radio-button>
            <a-radio-button value="B">B</a-radio-button>
        </a-radio-group>
        // 复选框
        <a-checkbox-group v-model="formState.ruleForm.productionAPIEndpoint">
            <a-checkbox value="A">A</a-checkbox>
            <a-checkbox value="B">B</a-checkbox>
        </a-checkbox-group>
        // 开关
        <a-switch checked-children="开" un-checked-children="关" v-model="formState.ruleForm.productionAPIEndpoint" />
        // 评分
        <a-rate v-model="formState.ruleForm.productionAPIEndpoint" allow-half />
        -->
    </a-form-model-item>
    <a-form-model-item label="stagingAPIEndpoint" prop="stagingAPIEndpoint" :rules="{ required: true, message: `请输入 stagingAPIEndpoint！`, trigger: 'blur' }" has-feedback>
        <a-input placeholder="请输入 stagingAPIEndpoint" v-model="formState.ruleForm.stagingAPIEndpoint" allowClear />
        <!-- 
        // 文本
        {{ stagingAPIEndpoint ?? "-" }}
        // 文本域
        <a-textarea placeholder="请输入 stagingAPIEndpoint" v-model="formState.ruleForm.stagingAPIEndpoint" allowClear show-count :rows="4" />
        // 日期选择框
        <a-date-picker placeholder="请选择 stagingAPIEndpoint" v-model="formState.ruleForm.stagingAPIEndpoint" allowClear style="width: 100%;" />
        // 下拉选择框
        <a-select placeholder="请选择 stagingAPIEndpoint" v-model="formState.ruleForm.stagingAPIEndpoint" allowClear>
            <a-select-option value="A" key="A">test</a-select-option>
            <a-select-option value="B" key="B">test</a-select-option>
        </a-select>
        // 单选框
        <a-radio-group v-model="formState.ruleForm.stagingAPIEndpoint">
            <a-radio-button value="A">A</a-radio-button>
            <a-radio-button value="B">B</a-radio-button>
        </a-radio-group>
        // 复选框
        <a-checkbox-group v-model="formState.ruleForm.stagingAPIEndpoint">
            <a-checkbox value="A">A</a-checkbox>
            <a-checkbox value="B">B</a-checkbox>
        </a-checkbox-group>
        // 开关
        <a-switch checked-children="开" un-checked-children="关" v-model="formState.ruleForm.stagingAPIEndpoint" />
        // 评分
        <a-rate v-model="formState.ruleForm.stagingAPIEndpoint" allow-half />
        -->
    </a-form-model-item>
    <a-form-model-item label="defaultPreferredChain" prop="defaultPreferredChain" :rules="{ required: true, message: `请输入 defaultPreferredChain！`, trigger: 'blur' }" has-feedback>
        <a-input placeholder="请输入 defaultPreferredChain" v-model="formState.ruleForm.defaultPreferredChain" allowClear />
        <!-- 
        // 文本
        {{ defaultPreferredChain ?? "-" }}
        // 文本域
        <a-textarea placeholder="请输入 defaultPreferredChain" v-model="formState.ruleForm.defaultPreferredChain" allowClear show-count :rows="4" />
        // 日期选择框
        <a-date-picker placeholder="请选择 defaultPreferredChain" v-model="formState.ruleForm.defaultPreferredChain" allowClear style="width: 100%;" />
        // 下拉选择框
        <a-select placeholder="请选择 defaultPreferredChain" v-model="formState.ruleForm.defaultPreferredChain" allowClear>
            <a-select-option value="A" key="A">test</a-select-option>
            <a-select-option value="B" key="B">test</a-select-option>
        </a-select>
        // 单选框
        <a-radio-group v-model="formState.ruleForm.defaultPreferredChain">
            <a-radio-button value="A">A</a-radio-button>
            <a-radio-button value="B">B</a-radio-button>
        </a-radio-group>
        // 复选框
        <a-checkbox-group v-model="formState.ruleForm.defaultPreferredChain">
            <a-checkbox value="A">A</a-checkbox>
            <a-checkbox value="B">B</a-checkbox>
        </a-checkbox-group>
        // 开关
        <a-switch checked-children="开" un-checked-children="关" v-model="formState.ruleForm.defaultPreferredChain" />
        // 评分
        <a-rate v-model="formState.ruleForm.defaultPreferredChain" allow-half />
        -->
    </a-form-model-item>
    <a-form-model-item label="isEnabled" prop="isEnabled" :rules="{ required: true, message: `请输入 isEnabled！`, trigger: 'blur' }" has-feedback>
        <a-input placeholder="请输入 isEnabled" v-model="formState.ruleForm.isEnabled" allowClear />
        <!-- 
        // 文本
        {{ isEnabled ?? "-" }}
        // 文本域
        <a-textarea placeholder="请输入 isEnabled" v-model="formState.ruleForm.isEnabled" allowClear show-count :rows="4" />
        // 日期选择框
        <a-date-picker placeholder="请选择 isEnabled" v-model="formState.ruleForm.isEnabled" allowClear style="width: 100%;" />
        // 下拉选择框
        <a-select placeholder="请选择 isEnabled" v-model="formState.ruleForm.isEnabled" allowClear>
            <a-select-option value="A" key="A">test</a-select-option>
            <a-select-option value="B" key="B">test</a-select-option>
        </a-select>
        // 单选框
        <a-radio-group v-model="formState.ruleForm.isEnabled">
            <a-radio-button value="A">A</a-radio-button>
            <a-radio-button value="B">B</a-radio-button>
        </a-radio-group>
        // 复选框
        <a-checkbox-group v-model="formState.ruleForm.isEnabled">
            <a-checkbox value="A">A</a-checkbox>
            <a-checkbox value="B">B</a-checkbox>
        </a-checkbox-group>
        // 开关
        <a-switch checked-children="开" un-checked-children="关" v-model="formState.ruleForm.isEnabled" />
        // 评分
        <a-rate v-model="formState.ruleForm.isEnabled" allow-half />
        -->
    </a-form-model-item>
    <a-form-model-item label="isCustom" prop="isCustom" :rules="{ required: true, message: `请输入 isCustom！`, trigger: 'blur' }" has-feedback>
        <a-input placeholder="请输入 isCustom" v-model="formState.ruleForm.isCustom" allowClear />
        <!-- 
        // 文本
        {{ isCustom ?? "-" }}
        // 文本域
        <a-textarea placeholder="请输入 isCustom" v-model="formState.ruleForm.isCustom" allowClear show-count :rows="4" />
        // 日期选择框
        <a-date-picker placeholder="请选择 isCustom" v-model="formState.ruleForm.isCustom" allowClear style="width: 100%;" />
        // 下拉选择框
        <a-select placeholder="请选择 isCustom" v-model="formState.ruleForm.isCustom" allowClear>
            <a-select-option value="A" key="A">test</a-select-option>
            <a-select-option value="B" key="B">test</a-select-option>
        </a-select>
        // 单选框
        <a-radio-group v-model="formState.ruleForm.isCustom">
            <a-radio-button value="A">A</a-radio-button>
            <a-radio-button value="B">B</a-radio-button>
        </a-radio-group>
        // 复选框
        <a-checkbox-group v-model="formState.ruleForm.isCustom">
            <a-checkbox value="A">A</a-checkbox>
            <a-checkbox value="B">B</a-checkbox>
        </a-checkbox-group>
        // 开关
        <a-switch checked-children="开" un-checked-children="关" v-model="formState.ruleForm.isCustom" />
        // 评分
        <a-rate v-model="formState.ruleForm.isCustom" allow-half />
        -->
    </a-form-model-item>
    <a-form-model-item label="sanLimit" prop="sanLimit" :rules="{ required: true, message: `请输入 sanLimit！`, trigger: 'blur' }" has-feedback>
        <a-input placeholder="请输入 sanLimit" v-model="formState.ruleForm.sanLimit" allowClear />
        <!-- 
        // 文本
        {{ sanLimit ?? "-" }}
        // 文本域
        <a-textarea placeholder="请输入 sanLimit" v-model="formState.ruleForm.sanLimit" allowClear show-count :rows="4" />
        // 日期选择框
        <a-date-picker placeholder="请选择 sanLimit" v-model="formState.ruleForm.sanLimit" allowClear style="width: 100%;" />
        // 下拉选择框
        <a-select placeholder="请选择 sanLimit" v-model="formState.ruleForm.sanLimit" allowClear>
            <a-select-option value="A" key="A">test</a-select-option>
            <a-select-option value="B" key="B">test</a-select-option>
        </a-select>
        // 单选框
        <a-radio-group v-model="formState.ruleForm.sanLimit">
            <a-radio-button value="A">A</a-radio-button>
            <a-radio-button value="B">B</a-radio-button>
        </a-radio-group>
        // 复选框
        <a-checkbox-group v-model="formState.ruleForm.sanLimit">
            <a-checkbox value="A">A</a-checkbox>
            <a-checkbox value="B">B</a-checkbox>
        </a-checkbox-group>
        // 开关
        <a-switch checked-children="开" un-checked-children="关" v-model="formState.ruleForm.sanLimit" />
        // 评分
        <a-rate v-model="formState.ruleForm.sanLimit" allow-half />
        -->
    </a-form-model-item>
    <a-form-model-item label="standardExpiryDays" prop="standardExpiryDays" :rules="{ required: true, message: `请输入 standardExpiryDays！`, trigger: 'blur' }" has-feedback>
        <a-input placeholder="请输入 standardExpiryDays" v-model="formState.ruleForm.standardExpiryDays" allowClear />
        <!-- 
        // 文本
        {{ standardExpiryDays ?? "-" }}
        // 文本域
        <a-textarea placeholder="请输入 standardExpiryDays" v-model="formState.ruleForm.standardExpiryDays" allowClear show-count :rows="4" />
        // 日期选择框
        <a-date-picker placeholder="请选择 standardExpiryDays" v-model="formState.ruleForm.standardExpiryDays" allowClear style="width: 100%;" />
        // 下拉选择框
        <a-select placeholder="请选择 standardExpiryDays" v-model="formState.ruleForm.standardExpiryDays" allowClear>
            <a-select-option value="A" key="A">test</a-select-option>
            <a-select-option value="B" key="B">test</a-select-option>
        </a-select>
        // 单选框
        <a-radio-group v-model="formState.ruleForm.standardExpiryDays">
            <a-radio-button value="A">A</a-radio-button>
            <a-radio-button value="B">B</a-radio-button>
        </a-radio-group>
        // 复选框
        <a-checkbox-group v-model="formState.ruleForm.standardExpiryDays">
            <a-checkbox value="A">A</a-checkbox>
            <a-checkbox value="B">B</a-checkbox>
        </a-checkbox-group>
        // 开关
        <a-switch checked-children="开" un-checked-children="关" v-model="formState.ruleForm.standardExpiryDays" />
        // 评分
        <a-rate v-model="formState.ruleForm.standardExpiryDays" allow-half />
        -->
    </a-form-model-item>
    <a-form-model-item label="requiresEmailAddress" prop="requiresEmailAddress" :rules="{ required: true, message: `请输入 requiresEmailAddress！`, trigger: 'blur' }" has-feedback>
        <a-input placeholder="请输入 requiresEmailAddress" v-model="formState.ruleForm.requiresEmailAddress" allowClear />
        <!-- 
        // 文本
        {{ requiresEmailAddress ?? "-" }}
        // 文本域
        <a-textarea placeholder="请输入 requiresEmailAddress" v-model="formState.ruleForm.requiresEmailAddress" allowClear show-count :rows="4" />
        // 日期选择框
        <a-date-picker placeholder="请选择 requiresEmailAddress" v-model="formState.ruleForm.requiresEmailAddress" allowClear style="width: 100%;" />
        // 下拉选择框
        <a-select placeholder="请选择 requiresEmailAddress" v-model="formState.ruleForm.requiresEmailAddress" allowClear>
            <a-select-option value="A" key="A">test</a-select-option>
            <a-select-option value="B" key="B">test</a-select-option>
        </a-select>
        // 单选框
        <a-radio-group v-model="formState.ruleForm.requiresEmailAddress">
            <a-radio-button value="A">A</a-radio-button>
            <a-radio-button value="B">B</a-radio-button>
        </a-radio-group>
        // 复选框
        <a-checkbox-group v-model="formState.ruleForm.requiresEmailAddress">
            <a-checkbox value="A">A</a-checkbox>
            <a-checkbox value="B">B</a-checkbox>
        </a-checkbox-group>
        // 开关
        <a-switch checked-children="开" un-checked-children="关" v-model="formState.ruleForm.requiresEmailAddress" />
        // 评分
        <a-rate v-model="formState.ruleForm.requiresEmailAddress" allow-half />
        -->
    </a-form-model-item>
    <a-form-model-item label="requiresExternalAccountBinding" prop="requiresExternalAccountBinding" :rules="{ required: true, message: `请输入 requiresExternalAccountBinding！`, trigger: 'blur' }" has-feedback>
        <a-input placeholder="请输入 requiresExternalAccountBinding" v-model="formState.ruleForm.requiresExternalAccountBinding" allowClear />
        <!-- 
        // 文本
        {{ requiresExternalAccountBinding ?? "-" }}
        // 文本域
        <a-textarea placeholder="请输入 requiresExternalAccountBinding" v-model="formState.ruleForm.requiresExternalAccountBinding" allowClear show-count :rows="4" />
        // 日期选择框
        <a-date-picker placeholder="请选择 requiresExternalAccountBinding" v-model="formState.ruleForm.requiresExternalAccountBinding" allowClear style="width: 100%;" />
        // 下拉选择框
        <a-select placeholder="请选择 requiresExternalAccountBinding" v-model="formState.ruleForm.requiresExternalAccountBinding" allowClear>
            <a-select-option value="A" key="A">test</a-select-option>
            <a-select-option value="B" key="B">test</a-select-option>
        </a-select>
        // 单选框
        <a-radio-group v-model="formState.ruleForm.requiresExternalAccountBinding">
            <a-radio-button value="A">A</a-radio-button>
            <a-radio-button value="B">B</a-radio-button>
        </a-radio-group>
        // 复选框
        <a-checkbox-group v-model="formState.ruleForm.requiresExternalAccountBinding">
            <a-checkbox value="A">A</a-checkbox>
            <a-checkbox value="B">B</a-checkbox>
        </a-checkbox-group>
        // 开关
        <a-switch checked-children="开" un-checked-children="关" v-model="formState.ruleForm.requiresExternalAccountBinding" />
        // 评分
        <a-rate v-model="formState.ruleForm.requiresExternalAccountBinding" allow-half />
        -->
    </a-form-model-item>
    <a-form-model-item label="allowUntrustedTls" prop="allowUntrustedTls" :rules="{ required: true, message: `请输入 allowUntrustedTls！`, trigger: 'blur' }" has-feedback>
        <a-input placeholder="请输入 allowUntrustedTls" v-model="formState.ruleForm.allowUntrustedTls" allowClear />
        <!-- 
        // 文本
        {{ allowUntrustedTls ?? "-" }}
        // 文本域
        <a-textarea placeholder="请输入 allowUntrustedTls" v-model="formState.ruleForm.allowUntrustedTls" allowClear show-count :rows="4" />
        // 日期选择框
        <a-date-picker placeholder="请选择 allowUntrustedTls" v-model="formState.ruleForm.allowUntrustedTls" allowClear style="width: 100%;" />
        // 下拉选择框
        <a-select placeholder="请选择 allowUntrustedTls" v-model="formState.ruleForm.allowUntrustedTls" allowClear>
            <a-select-option value="A" key="A">test</a-select-option>
            <a-select-option value="B" key="B">test</a-select-option>
        </a-select>
        // 单选框
        <a-radio-group v-model="formState.ruleForm.allowUntrustedTls">
            <a-radio-button value="A">A</a-radio-button>
            <a-radio-button value="B">B</a-radio-button>
        </a-radio-group>
        // 复选框
        <a-checkbox-group v-model="formState.ruleForm.allowUntrustedTls">
            <a-checkbox value="A">A</a-checkbox>
            <a-checkbox value="B">B</a-checkbox>
        </a-checkbox-group>
        // 开关
        <a-switch checked-children="开" un-checked-children="关" v-model="formState.ruleForm.allowUntrustedTls" />
        // 评分
        <a-rate v-model="formState.ruleForm.allowUntrustedTls" allow-half />
        -->
    </a-form-model-item>
    <a-form-model-item label="allowInternalHostnames" prop="allowInternalHostnames" :rules="{ required: true, message: `请输入 allowInternalHostnames！`, trigger: 'blur' }" has-feedback>
        <a-input placeholder="请输入 allowInternalHostnames" v-model="formState.ruleForm.allowInternalHostnames" allowClear />
        <!-- 
        // 文本
        {{ allowInternalHostnames ?? "-" }}
        // 文本域
        <a-textarea placeholder="请输入 allowInternalHostnames" v-model="formState.ruleForm.allowInternalHostnames" allowClear show-count :rows="4" />
        // 日期选择框
        <a-date-picker placeholder="请选择 allowInternalHostnames" v-model="formState.ruleForm.allowInternalHostnames" allowClear style="width: 100%;" />
        // 下拉选择框
        <a-select placeholder="请选择 allowInternalHostnames" v-model="formState.ruleForm.allowInternalHostnames" allowClear>
            <a-select-option value="A" key="A">test</a-select-option>
            <a-select-option value="B" key="B">test</a-select-option>
        </a-select>
        // 单选框
        <a-radio-group v-model="formState.ruleForm.allowInternalHostnames">
            <a-radio-button value="A">A</a-radio-button>
            <a-radio-button value="B">B</a-radio-button>
        </a-radio-group>
        // 复选框
        <a-checkbox-group v-model="formState.ruleForm.allowInternalHostnames">
            <a-checkbox value="A">A</a-checkbox>
            <a-checkbox value="B">B</a-checkbox>
        </a-checkbox-group>
        // 开关
        <a-switch checked-children="开" un-checked-children="关" v-model="formState.ruleForm.allowInternalHostnames" />
        // 评分
        <a-rate v-model="formState.ruleForm.allowInternalHostnames" allow-half />
        -->
    </a-form-model-item>
    <a-form-model-item label="supportsCachedValidations" prop="supportsCachedValidations" :rules="{ required: true, message: `请输入 supportsCachedValidations！`, trigger: 'blur' }" has-feedback>
        <a-input placeholder="请输入 supportsCachedValidations" v-model="formState.ruleForm.supportsCachedValidations" allowClear />
        <!-- 
        // 文本
        {{ supportsCachedValidations ?? "-" }}
        // 文本域
        <a-textarea placeholder="请输入 supportsCachedValidations" v-model="formState.ruleForm.supportsCachedValidations" allowClear show-count :rows="4" />
        // 日期选择框
        <a-date-picker placeholder="请选择 supportsCachedValidations" v-model="formState.ruleForm.supportsCachedValidations" allowClear style="width: 100%;" />
        // 下拉选择框
        <a-select placeholder="请选择 supportsCachedValidations" v-model="formState.ruleForm.supportsCachedValidations" allowClear>
            <a-select-option value="A" key="A">test</a-select-option>
            <a-select-option value="B" key="B">test</a-select-option>
        </a-select>
        // 单选框
        <a-radio-group v-model="formState.ruleForm.supportsCachedValidations">
            <a-radio-button value="A">A</a-radio-button>
            <a-radio-button value="B">B</a-radio-button>
        </a-radio-group>
        // 复选框
        <a-checkbox-group v-model="formState.ruleForm.supportsCachedValidations">
            <a-checkbox value="A">A</a-checkbox>
            <a-checkbox value="B">B</a-checkbox>
        </a-checkbox-group>
        // 开关
        <a-switch checked-children="开" un-checked-children="关" v-model="formState.ruleForm.supportsCachedValidations" />
        // 评分
        <a-rate v-model="formState.ruleForm.supportsCachedValidations" allow-half />
        -->
    </a-form-model-item>
    <a-form-model-item label="eabInstructions" prop="eabInstructions" :rules="{ required: true, message: `请输入 eabInstructions！`, trigger: 'blur' }" has-feedback>
        <a-input placeholder="请输入 eabInstructions" v-model="formState.ruleForm.eabInstructions" allowClear />
        <!-- 
        // 文本
        {{ eabInstructions ?? "-" }}
        // 文本域
        <a-textarea placeholder="请输入 eabInstructions" v-model="formState.ruleForm.eabInstructions" allowClear show-count :rows="4" />
        // 日期选择框
        <a-date-picker placeholder="请选择 eabInstructions" v-model="formState.ruleForm.eabInstructions" allowClear style="width: 100%;" />
        // 下拉选择框
        <a-select placeholder="请选择 eabInstructions" v-model="formState.ruleForm.eabInstructions" allowClear>
            <a-select-option value="A" key="A">test</a-select-option>
            <a-select-option value="B" key="B">test</a-select-option>
        </a-select>
        // 单选框
        <a-radio-group v-model="formState.ruleForm.eabInstructions">
            <a-radio-button value="A">A</a-radio-button>
            <a-radio-button value="B">B</a-radio-button>
        </a-radio-group>
        // 复选框
        <a-checkbox-group v-model="formState.ruleForm.eabInstructions">
            <a-checkbox value="A">A</a-checkbox>
            <a-checkbox value="B">B</a-checkbox>
        </a-checkbox-group>
        // 开关
        <a-switch checked-children="开" un-checked-children="关" v-model="formState.ruleForm.eabInstructions" />
        // 评分
        <a-rate v-model="formState.ruleForm.eabInstructions" allow-half />
        -->
    </a-form-model-item>
    <a-form-model-item label="supportedKeyTypes" prop="supportedKeyTypes" :rules="{ required: true, message: `请输入 supportedKeyTypes！`, trigger: 'blur' }" has-feedback>
        <a-input placeholder="请输入 supportedKeyTypes" v-model="formState.ruleForm.supportedKeyTypes" allowClear />
        <!-- 
        // 文本
        {{ supportedKeyTypes ?? "-" }}
        // 文本域
        <a-textarea placeholder="请输入 supportedKeyTypes" v-model="formState.ruleForm.supportedKeyTypes" allowClear show-count :rows="4" />
        // 日期选择框
        <a-date-picker placeholder="请选择 supportedKeyTypes" v-model="formState.ruleForm.supportedKeyTypes" allowClear style="width: 100%;" />
        // 下拉选择框
        <a-select placeholder="请选择 supportedKeyTypes" v-model="formState.ruleForm.supportedKeyTypes" allowClear>
            <a-select-option value="A" key="A">test</a-select-option>
            <a-select-option value="B" key="B">test</a-select-option>
        </a-select>
        // 单选框
        <a-radio-group v-model="formState.ruleForm.supportedKeyTypes">
            <a-radio-button value="A">A</a-radio-button>
            <a-radio-button value="B">B</a-radio-button>
        </a-radio-group>
        // 复选框
        <a-checkbox-group v-model="formState.ruleForm.supportedKeyTypes">
            <a-checkbox value="A">A</a-checkbox>
            <a-checkbox value="B">B</a-checkbox>
        </a-checkbox-group>
        // 开关
        <a-switch checked-children="开" un-checked-children="关" v-model="formState.ruleForm.supportedKeyTypes" />
        // 评分
        <a-rate v-model="formState.ruleForm.supportedKeyTypes" allow-half />
        -->
    </a-form-model-item>
    <a-form-model-item label="disabledIntermediates" prop="disabledIntermediates" :rules="{ required: true, message: `请输入 disabledIntermediates！`, trigger: 'blur' }" has-feedback>
        <a-input placeholder="请输入 disabledIntermediates" v-model="formState.ruleForm.disabledIntermediates" allowClear />
        <!-- 
        // 文本
        {{ disabledIntermediates ?? "-" }}
        // 文本域
        <a-textarea placeholder="请输入 disabledIntermediates" v-model="formState.ruleForm.disabledIntermediates" allowClear show-count :rows="4" />
        // 日期选择框
        <a-date-picker placeholder="请选择 disabledIntermediates" v-model="formState.ruleForm.disabledIntermediates" allowClear style="width: 100%;" />
        // 下拉选择框
        <a-select placeholder="请选择 disabledIntermediates" v-model="formState.ruleForm.disabledIntermediates" allowClear>
            <a-select-option value="A" key="A">test</a-select-option>
            <a-select-option value="B" key="B">test</a-select-option>
        </a-select>
        // 单选框
        <a-radio-group v-model="formState.ruleForm.disabledIntermediates">
            <a-radio-button value="A">A</a-radio-button>
            <a-radio-button value="B">B</a-radio-button>
        </a-radio-group>
        // 复选框
        <a-checkbox-group v-model="formState.ruleForm.disabledIntermediates">
            <a-checkbox value="A">A</a-checkbox>
            <a-checkbox value="B">B</a-checkbox>
        </a-checkbox-group>
        // 开关
        <a-switch checked-children="开" un-checked-children="关" v-model="formState.ruleForm.disabledIntermediates" />
        // 评分
        <a-rate v-model="formState.ruleForm.disabledIntermediates" allow-half />
        -->
    </a-form-model-item>
    <a-form-model-item label="trustedRoots" prop="trustedRoots" :rules="{ required: true, message: `请输入 trustedRoots！`, trigger: 'blur' }" has-feedback>
        <a-input placeholder="请输入 trustedRoots" v-model="formState.ruleForm.trustedRoots" allowClear />
        <!-- 
        // 文本
        {{ trustedRoots ?? "-" }}
        // 文本域
        <a-textarea placeholder="请输入 trustedRoots" v-model="formState.ruleForm.trustedRoots" allowClear show-count :rows="4" />
        // 日期选择框
        <a-date-picker placeholder="请选择 trustedRoots" v-model="formState.ruleForm.trustedRoots" allowClear style="width: 100%;" />
        // 下拉选择框
        <a-select placeholder="请选择 trustedRoots" v-model="formState.ruleForm.trustedRoots" allowClear>
            <a-select-option value="A" key="A">test</a-select-option>
            <a-select-option value="B" key="B">test</a-select-option>
        </a-select>
        // 单选框
        <a-radio-group v-model="formState.ruleForm.trustedRoots">
            <a-radio-button value="A">A</a-radio-button>
            <a-radio-button value="B">B</a-radio-button>
        </a-radio-group>
        // 复选框
        <a-checkbox-group v-model="formState.ruleForm.trustedRoots">
            <a-checkbox value="A">A</a-checkbox>
            <a-checkbox value="B">B</a-checkbox>
        </a-checkbox-group>
        // 开关
        <a-switch checked-children="开" un-checked-children="关" v-model="formState.ruleForm.trustedRoots" />
        // 评分
        <a-rate v-model="formState.ruleForm.trustedRoots" allow-half />
        -->
    </a-form-model-item>
    <a-form-model-item label="intermediates" prop="intermediates" :rules="{ required: true, message: `请输入 intermediates！`, trigger: 'blur' }" has-feedback>
        <a-input placeholder="请输入 intermediates" v-model="formState.ruleForm.intermediates" allowClear />
        <!-- 
        // 文本
        {{ intermediates ?? "-" }}
        // 文本域
        <a-textarea placeholder="请输入 intermediates" v-model="formState.ruleForm.intermediates" allowClear show-count :rows="4" />
        // 日期选择框
        <a-date-picker placeholder="请选择 intermediates" v-model="formState.ruleForm.intermediates" allowClear style="width: 100%;" />
        // 下拉选择框
        <a-select placeholder="请选择 intermediates" v-model="formState.ruleForm.intermediates" allowClear>
            <a-select-option value="A" key="A">test</a-select-option>
            <a-select-option value="B" key="B">test</a-select-option>
        </a-select>
        // 单选框
        <a-radio-group v-model="formState.ruleForm.intermediates">
            <a-radio-button value="A">A</a-radio-button>
            <a-radio-button value="B">B</a-radio-button>
        </a-radio-group>
        // 复选框
        <a-checkbox-group v-model="formState.ruleForm.intermediates">
            <a-checkbox value="A">A</a-checkbox>
            <a-checkbox value="B">B</a-checkbox>
        </a-checkbox-group>
        // 开关
        <a-switch checked-children="开" un-checked-children="关" v-model="formState.ruleForm.intermediates" />
        // 评分
        <a-rate v-model="formState.ruleForm.intermediates" allow-half />
        -->
    </a-form-model-item>
</a-form-model>
*/

//#endregion

export class FileResponse {
    data: Blob | undefined;
    status: number | undefined;
    fileName?: string | undefined;
    headers?: { [name: string]: any };
}

export interface FileParameter {
    data: any;
    fileName: string;
}